name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: my-robo-org
      SENTRY_PROJECT: home-budget
      SENTRY_ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Compute SENTRY_RELEASE
        run: echo "SENTRY_RELEASE=$(npx sentry-cli releases propose-version)" >> $GITHUB_ENV

      - name: Inject SENTRY_RELEASE into app env
        run: echo "export const SENTRY_RELEASE = '${{ env.SENTRY_RELEASE }}';" > sentry/environments.ts

      - name: Build
        run: npm run build

      - name: Create Sentry release
        run: npx sentry-cli releases new -p "$SENTRY_PROJECT" "$SENTRY_RELEASE"

      - name: Associate commits
        run: npx sentry-cli releases set-commits --auto "$SENTRY_RELEASE"

      - name: Upload sourcemaps to Sentry
        run: |
          npx sentry-cli sourcemaps inject ./dist
          npx sentry-cli sourcemaps upload ./dist --release "$SENTRY_RELEASE"

      - name: Finalize release & mark deploy
        run: |
          npx sentry-cli releases finalize "$SENTRY_RELEASE"
          npx sentry-cli releases deploys "$SENTRY_RELEASE" new -e "$SENTRY_ENVIRONMENT"

      - name: Clean up local sourcemaps
        run: rm -rf dist/home-budget/browser/*.map

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOME_BUDGET_897C3 }}
          channelId: live
          projectId: home-budget-897c3
